import type { Metadata } from "next";
import { MarketingShell } from "../site-chrome";

export const metadata: Metadata = { title: "Subprocessors", description: "The subprocessors currently used to host, protect and deliver CoreCare services.", alternates: { canonical: "/subprocessors" } };

export default function SubprocessorsPage() {
  return <MarketingShell><section className="content-hero compact-content-hero"><div className="site-shell narrow-heading"><p className="eyebrow">Subprocessors</p><h1>The suppliers behind CoreCare delivery.</h1><p className="content-lead">This list covers suppliers that may process customer personal data for the hosted CoreCare suite. A supplier is included only for the services actually enabled for a customer.</p><p className="updated-note">Last reviewed 7 August 2026</p></div></section><section className="section legal-section"><div className="site-shell legal-copy">
    <div className="legal-table-wrap"><table><thead><tr><th>Supplier</th><th>Role and purpose</th><th>Data and location notes</th></tr></thead><tbody><tr><td>Cloudflare, Inc. and relevant group entities</td><td>Processor/subprocessor for network delivery and security, Workers application hosting, D1 database, R2 object storage where configured, service observability, identity protection and optional Workers AI text rewriting initiated by an authorised user.</td><td>Account, product, technical, security and hosted customer data as required by the enabled service. Text is sent for AI rewriting only when a signed-in user selects Generate; CoreCare records usage metadata but does not store the source text or suggestion in its AI usage log. Cloudflare operates an international network; applicable contractual transfer safeguards are used for restricted transfers.</td></tr><tr><td>Stripe Payments Europe, Limited and relevant Stripe group entities</td><td>Payment service for live subscription checkout, payment administration, fraud prevention and related financial compliance. Stripe may act as processor for some activities and independent controller for regulated payment activities.</td><td>Billing contact, subscription, transaction, device and payment-method information when a person actively opens live Stripe checkout. Payment-card details are collected by Stripe, not by the CoreCare website. Stripe may process data internationally using the safeguards in its DPA and transfer addendum.</td></tr></tbody></table></div>
    <h2>AI rewriting, payment and optional integrations</h2><p>The optional rewrite feature sends only the text a signed-in user actively submits. It does not rewrite, replace, save or send wording automatically; the user must review and choose whether to apply the suggestion. Users should follow their organisation’s rules about entering confidential or special-category information.</p><p>Stripe is listed because live subscription checkout is offered after a trial. It is not a product database and does not receive customer care, booking, workshop, finance-ledger or POS operational records through this checkout. Read <a href="https://stripe.com/gb/privacy" rel="noreferrer">Stripe’s privacy notice</a> and <a href="https://stripe.com/legal/dpa" rel="noreferrer">Stripe’s DPA</a> for its current roles and safeguards.</p><p>Another integration is not automatically a Subprocessor for every CoreCare product. Where a customer enables an optional service that processes Customer Personal Data, the applicable order and this list will identify it before production use.</p>
    <h2>Changes and objections</h2><p>Customers may subscribe to change notices by emailing <a href="mailto:privacy@corecaresystems.co.uk?subject=Subprocessor%20change%20notices">privacy@corecaresystems.co.uk</a>. CoreCare will give reasonable advance notice of a new or replacement Subprocessor where practicable. A customer may raise a reasonable data-protection objection under the DPA.</p>
  </div></section></MarketingShell>;
}
