import type { Metadata } from "next";
import Link from "next/link";
import { COMPANY_ADDRESS, COMPANY_DETAILS, CONTRACTING_NAME } from "../company-details";
import { Arrow, MarketingShell } from "../site-chrome";

export const metadata: Metadata = { title: "About CoreCare Systems", description: "Meet the independent UK business behind CoreCare Care, Campsites, Finance, Garage and POS.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <MarketingShell><section className="content-hero"><div className="site-shell narrow-heading"><p className="eyebrow">About CoreCare Systems</p><h1>Practical software, built close to the work.</h1><p className="content-lead">CoreCare Systems is an independent UK software business creating focused products for care, leisure, finance, workshop and hospitality operations.</p></div></section>
    <section className="section"><div className="site-shell product-story-grid"><div><p className="eyebrow">The business</p><h2>One accountable supplier.</h2><p>{CONTRACTING_NAME} is responsible for the business and the CoreCare product family. CoreCare operates from {COMPANY_ADDRESS} and supports customers through the contact routes published on this website.</p><p>The aim is straightforward: reduce the daily chasing created by disconnected records, messages and spreadsheets, while being honest about what is ready to evaluate and what must be confirmed before live use.</p><Link className="secondary-button" href="/legal">View legal details <Arrow /></Link></div><div className="feature-stack"><article><span>01</span><div><h3>Focused by sector</h3><p>Each product follows the language and operational decisions of the work it supports.</p></div></article><article><span>02</span><div><h3>Shared standards</h3><p>The suite uses consistent expectations for onboarding, privacy, security and support.</p></div></article><article><span>03</span><div><h3>Evidence before claims</h3><p>Features, integrations, customer results and assurance are published only when they can be supported.</p></div></article><article><span>04</span><div><h3>Direct accountability</h3><p>Questions about scope, contracts, privacy or readiness have a clear route back to the business.</p></div></article></div></div></section>
    <section className="section process-section"><div className="site-shell evidence-grid"><article><p className="eyebrow">Customer evidence</p><h2>No invented proof.</h2><p>CoreCare will publish named case studies, testimonials and measured outcomes only with the customer’s permission and enough context to make them meaningful. Representative demonstrations are clearly labelled until genuine evidence is available.</p></article><article><p className="eyebrow">Talk directly</p><h2>Start with your workflow.</h2><p>Tell us what your team does today, where time is being lost and which controls matter. We will show the relevant product and identify gaps before asking you to rely on it.</p><Link href="/contact">Contact {COMPANY_DETAILS.legalName} <Arrow /></Link></article></div></section>
  </MarketingShell>;
}
