import type { Metadata } from "next";
import Link from "next/link";
import { COMPANY_ADDRESS, COMPANY_DETAILS } from "../company-details";
import { MarketingShell } from "../site-chrome";

export const metadata: Metadata = { title: "Privacy notice", description: "How CoreCare Systems handles website, enquiry, trial, customer and product personal information.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <MarketingShell><section className="content-hero compact-content-hero"><div className="site-shell narrow-heading"><p className="eyebrow">Privacy notice</p><h1>How we use your information.</h1><p className="content-lead">This notice explains what CoreCare collects, why it is used, who receives it, how long it is kept and how to exercise your rights.</p><p className="updated-note">Version 2.0 · 5 August 2026</p></div></section><section className="section legal-section"><div className="site-shell legal-copy">
    <h2>Who we are</h2><p>{COMPANY_DETAILS.legalName} (“CoreCare”, “we”, “us”) is the controller for personal information used to run this website, answer enquiries, manage trials, administer customers, protect accounts and operate our own business. Our trading address is {COMPANY_ADDRESS}, {COMPANY_DETAILS.country}. Contact <a href="mailto:privacy@corecaresystems.co.uk">privacy@corecaresystems.co.uk</a> or telephone <a href={`tel:${COMPANY_DETAILS.telephoneHref}`}>{COMPANY_DETAILS.telephoneDisplay}</a>. CoreCare has no company number, is not VAT registered and is registered with the Information Commissioner’s Office under reference {COMPANY_DETAILS.icoRegistrationNumber}.</p>
    <h2>When a customer is the controller</h2><p>For personal information a subscribing organisation enters into a CoreCare product, that organisation will normally be controller and CoreCare will act as processor under the <Link href="/data-processing-agreement">customer DPA</Link>. The customer decides why the records are used, who can access them and how long they are required. A request about those records should normally go first to that organisation; CoreCare will assist it.</p>
    <h2>Information we collect</h2><ul><li><strong>Enquiries and trials:</strong> name, work email, organisation, optional telephone number, team size, selected product, message and setup status.</li><li><strong>Accounts and customer administration:</strong> identity, contact, role, permissions, organisation, subscription, billing administration, support and service communications.</li><li><strong>Privacy and security requests:</strong> contact details, relationship, request scope, verification status, actions, decisions and communications. Identity evidence is requested separately only where proportionate.</li><li><strong>Technical and security information:</strong> request time, network address or a protective hash, browser or device information, requested route, form outcome, authentication and audit events.</li><li><strong>Customer product information:</strong> the records, attachments and activity needed to provide the selected service under the customer’s instructions.</li></ul>
    <h2>Purposes and lawful bases</h2><div className="legal-table-wrap"><table><thead><tr><th>Purpose</th><th>Lawful basis</th></tr></thead><tbody><tr><td>Answer an enquiry, prepare a trial or enter a customer agreement.</td><td>Steps at your request before a contract and legitimate interests in responding to genuine business enquiries.</td></tr><tr><td>Provide, secure and support a purchased service.</td><td>Performance of a contract and legitimate interests in reliable service administration.</td></tr><tr><td>Prevent misuse, investigate faults and protect accounts and services.</td><td>Legitimate interests in security, fraud prevention and service integrity; legal obligation where applicable.</td></tr><tr><td>Handle privacy requests, incidents, tax, accounting and legal claims.</td><td>Legal obligation and legitimate interests in accountability and establishing or defending claims.</td></tr></tbody></table></div><p>Where we rely on legitimate interests, we assess the purpose, necessity and effect on people. We do not use these website forms for direct marketing enrolment. If that changes, a clear choice and lawful unsubscribe route will be provided.</p>
    <h2>Required information and sensitive records</h2><p>Required form fields let us identify the service, reply safely and prevent misuse. Optional fields are marked. Public forms are not intended for passwords, payment-card details, health or care records, identity documents or children’s information. Do not put those records in a general enquiry. Special-category product data is processed only where the ordered product, customer instructions and lawful safeguards require it.</p>
    <h2>Recipients and subprocessors</h2><p>Access is limited to authorised CoreCare personnel and suppliers that need the information to host, protect or support the enabled service. Cloudflare provides network, security, application hosting, database and object-storage services. The current <Link href="/subprocessors">subprocessor list</Link> describes enabled suppliers. We do not sell personal information.</p>
    <h2>International processing</h2><p>Cloudflare operates an international network, so limited service information may be processed outside the UK. Where a restricted transfer applies, CoreCare relies on the provider’s applicable contractual transfer mechanism and supplementary measures. Contact us for information about the safeguard relevant to your service. We do not claim a UK-only storage location unless the customer order expressly confirms it.</p>
    <h2>Retention</h2><p>We keep information only while its purpose, a customer instruction, a security need or a legal duty justifies it. The published <Link href="/data-retention">retention policy</Link> sets baseline periods and explains legal holds, product-specific instructions and end-of-service deletion. Where a fixed period is not appropriate, we document the review criteria and action.</p>
    <h2>Automated processing</h2><p>Security checks, rate limits, subscription status and account routing use automated rules. CoreCare does not use public-website information to make a solely automated decision with legal or similarly significant effects. A trial request is not automatic approval for production use.</p>
    <h2>Your rights</h2><p>Depending on the information and lawful basis, you may have rights of access, correction, erasure, restriction, portability and objection. These rights are not absolute. You may object to processing based on legitimate interests and to direct marketing at any time. Use the <Link href="/data-rights">privacy request form</Link>, email <a href="mailto:privacy@corecaresystems.co.uk">privacy@corecaresystems.co.uk</a> or contact us by post. Requests may be verbal or written. We normally respond without undue delay and within one calendar month, subject to lawful clarification, identity checks or an explained extension.</p>
    <h2>Complaints and changes</h2><p>Tell us first if you would like us to investigate. You may also complain to the UK Information Commissioner’s Office through <a href="https://ico.org.uk/make-a-complaint/" rel="noreferrer">ico.org.uk/make-a-complaint</a>. We review this notice when our products, providers or legal obligations change and publish the new date and version here.</p>
  </div></section></MarketingShell>;
}
