import type { Metadata } from "next";
import { MarketingShell } from "../site-chrome";

export const metadata: Metadata = { title: "Privacy notice", description: "How CoreCare Systems handles website, enquiry, trial and product personal information.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <MarketingShell><section className="content-hero compact-content-hero"><div className="site-shell narrow-heading"><p className="eyebrow">Privacy notice</p><h1>How we use your information.</h1><p className="content-lead">This notice covers the public CoreCare Systems website, contact and account-help enquiries, trial requests and the relationship between CoreCare and product customers.</p><p className="updated-note">Last updated 5 August 2026</p></div></section><section className="section legal-section"><div className="site-shell legal-copy">
    <h2>Who we are</h2><p>CoreCare Systems (“CoreCare”, “we”, “us”) operates this website and is the controller for enquiries and trial requests submitted directly to us. Contact <a href="mailto:privacy@corecaresystems.co.uk">privacy@corecaresystems.co.uk</a> about this notice. The contracting legal entity and service address are stated in the relevant customer order and must be checked before entering an agreement.</p>
    <h2>Our role in customer products</h2><p>For personal information an organisation puts into a CoreCare product, that customer will normally be the controller and CoreCare will act as its processor under the customer agreement. The customer decides why the information is used, which users have access and how long product records are needed. Requests about a product record should normally go first to that organisation.</p>
    <h2>Information we collect</h2><ul><li><strong>Enquiry and trial details:</strong> name, work email, organisation, optional phone number, team size, selected product and message.</li><li><strong>Account-help details:</strong> name, work email, organisation and the product for which help is requested.</li><li><strong>Technical and security information:</strong> request time, network address, browser or device information, requested page, form outcome and security events.</li><li><strong>Customer product information:</strong> account, role, support and service information processed under the relevant customer agreement.</li></ul>
    <h2>Purposes and lawful bases</h2><ul><li>Respond to an enquiry or arrange a trial: steps at your request before a contract and our legitimate interest in answering genuine business enquiries.</li><li>Set up, operate and support a customer service: performance of a contract and our legitimate interest in providing reliable support.</li><li>Protect forms, accounts and services: our legitimate interest in preventing misuse, investigating faults and keeping CoreCare secure.</li><li>Keep legal, accounting and dispute records: compliance with legal obligations and, where applicable, our legitimate interest in establishing or defending claims.</li></ul><p>Our legitimate interests are limited to running, improving and protecting CoreCare in ways a business user would reasonably expect. We consider the effect on people before relying on this basis.</p>
    <h2>Is the information required?</h2><p>Required form fields are needed to identify the organisation, respond safely and provide the requested service. Optional fields are marked. If required information is not provided, we may be unable to respond, verify a requester or prepare a trial.</p>
    <h2>Special-category and children’s information</h2><p>The public website forms are not intended for health records, care records, children’s information, payment details or passwords. Do not submit them through an enquiry or trial form. A care customer may use CoreCare Care for sensitive records under its own lawful basis, governance and controller responsibilities; those arrangements must be agreed before real data is introduced.</p>
    <h2>Recipients and service providers</h2><p>Access is limited to authorised CoreCare personnel and providers that need information to host, protect or support the service. Cloudflare provides website delivery, security, application hosting and data services. A current provider list and relevant data-processing terms can be requested from <a href="mailto:privacy@corecaresystems.co.uk">privacy@corecaresystems.co.uk</a>. We do not sell personal information.</p>
    <h2>International processing</h2><p>Cloudflare operates an international network, so limited technical or service information may be processed outside the UK. Where restricted transfers apply, contractual safeguards and other measures described in the provider’s data-processing terms are used. You may request information about the applicable safeguard from us.</p>
    <h2>Retention</h2><p>We keep each category only while it is needed for the stated purpose. The criteria include whether an enquiry remains active, whether a trial or contract follows, the customer’s documented instructions, security and audit needs, limitation periods, and legal or accounting duties. Product retention, export and deletion arrangements are confirmed in the customer agreement. We review records when the purpose ends and delete or anonymise them when no longer required.</p>
    <h2>Automated processing</h2><p>Security checks and account routing use automated rules, but CoreCare does not use public-website information to make a solely automated decision with legal or similarly significant effects. A trial request is not automatic approval for production use.</p>
    <h2>Your rights</h2><p>Depending on the information and lawful basis, you may have rights of access, correction, erasure, restriction, portability and objection. These rights are not absolute. <strong>You may object at any time to processing based on legitimate interests and to any direct marketing.</strong> CoreCare does not currently use these website forms to enrol you in marketing.</p>
    <h2>Complaints and contact</h2><p>Email <a href="mailto:privacy@corecaresystems.co.uk">privacy@corecaresystems.co.uk</a>. Please do not send passwords or sensitive product records by ordinary email. You may also complain to the UK Information Commissioner’s Office at <a href="https://ico.org.uk/make-a-complaint/" rel="noreferrer">ico.org.uk/make-a-complaint</a>.</p>
  </div></section></MarketingShell>;
}
