"use client";

import Link from "next/link";
import { useState } from "react";
import { PRODUCTS, type CoreCareProduct } from "./products";

function Brand({ inverse = false }: { inverse?: boolean }) {
  return <span className={`brand-lockup${inverse ? " inverse" : ""}`}><span className="brand-mark" aria-hidden="true"><i /><i /></span><span><strong>CoreCare</strong><small>Systems</small></span></span>;
}
const Arrow = () => <span aria-hidden="true">↗</span>;

function ProductMock({ product, compact = false }: { product: CoreCareProduct; compact?: boolean }) {
  const rows: Record<string, string[][]> = {
    CARE: [["Morning care · Elsie Bennett", "09:30 · Emma R.", "In progress"], ["Medication round · Oak Wing", "10:00 · 8 people", "Due soon"], ["Care plan review · J. Thompson", "11:15 · Manager review", "Ready"]],
    CAMPSITE: [["Meadow 12 · The Harris family", "Arriving today · 4 nights", "Confirmed"], ["Willow Pod · M. Carter", "Checking out · 10:00", "On site"], ["Lakeview 4 · Direct booking", "Friday · £164 balance", "New"]],
    FINANCE: [["Sales invoices", "18 awaiting payment", "£12,840"], ["Bank reconciliation", "Current account · today", "6 to match"], ["VAT position", "Quarter ending September", "On track"]],
    GARAGE: [["AB12 CDE · Full service", "Bay 2 · Liam", "In progress"], ["EF34 GHI · MOT", "Bay 1 · 10:30", "Inspection"], ["JK56 LMN · Brakes", "Parts received", "Ready"]],
    POS: [["Table 12 · 4 covers", "Kitchen · 8 mins", "Cooking"], ["Collection #1042", "2 items · paid", "Ready"], ["Table 7 · 2 covers", "Drinks served", "Open"]],
    PLATFORM: [["CoreCare Care", "Production · v1.33.0", "Healthy"], ["CoreCare POS", "Production · v1.4.0", "Healthy"], ["CoreCare Garage", "Production · v0.8.0", "Healthy"]],
  };
  return <div className={`product-mock${compact ? " compact-mock" : ""}`} style={{ "--product-accent": product.accent, "--product-soft": product.soft } as React.CSSProperties}>
    <div className="mock-sidebar" aria-hidden="true"><span className="mock-logo">C</span><span className="mock-nav active" /><span className="mock-nav" /><span className="mock-nav" /><span className="mock-nav short" /><span className="mock-avatar" /></div>
    <div className="mock-workspace"><div className="mock-topbar"><span><small>{product.name}</small><strong>Good morning, Alex</strong></span><i>⌕</i><b>AR</b></div><div className="mock-content">
      <div className="mock-heading"><span><small>Today at a glance</small><strong>{product.metric.label}</strong></span><button>+ New</button></div>
      <div className="mock-metrics"><article><small>{product.metric.label}</small><strong>{product.metric.value}</strong><span>{product.metric.detail}</span></article><article><small>Needs attention</small><strong>{product.code === "FINANCE" ? "6" : "2"}</strong><span>Prioritised for you</span></article><article><small>Team activity</small><strong>{product.code === "CAMPSITE" ? "18" : "24"}</strong><span>Updates today</span></article></div>
      <div className="mock-panel"><div className="mock-panel-head"><strong>Live workspace</strong><span>View all</span></div>{rows[product.code].map((row, index) => <div className="mock-row" key={row[0]}><i>{index + 1}</i><span><strong>{row[0]}</strong><small>{row[1]}</small></span><em>{row[2]}</em></div>)}</div>
    </div></div>
  </div>;
}

export default function HomeClient() {
  const [activeProduct, setActiveProduct] = useState(PRODUCTS[0]);
  const [mobileOpen, setMobileOpen] = useState(false);
  return <main>
    <header className="site-header"><div className="site-shell nav-shell"><Link href="/" aria-label="CoreCare Systems home"><Brand /></Link><button className="menu-button" aria-label="Toggle navigation" aria-expanded={mobileOpen} onClick={() => setMobileOpen(!mobileOpen)}>Menu</button><nav className={mobileOpen ? "open" : ""} aria-label="Main navigation"><a href="#products">Products</a><a href="#demo">See it in action</a><a href="#why-corecare">Why CoreCare</a><a href="#questions">Questions</a></nav><div className="nav-actions"><Link className="text-link" href="/login">Log in</Link><Link className="button small-button" href="/trial">Start free trial <Arrow /></Link></div></div></header>
    <section className="hero"><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /><div className="site-shell hero-grid">
      <div className="hero-copy"><p className="eyebrow"><span>Connected business software</span></p><h1>One front door.<br /><em>Every CoreCare product.</em></h1><p className="hero-lead">Run care, campsites, finance, garages and hospitality with focused software that feels like one joined-up system.</p><div className="hero-actions"><Link className="button" href="/trial">Start your 30-day trial <Arrow /></Link><a className="secondary-button" href="#demo">Explore the products <span>↓</span></a></div><div className="hero-proof"><span><i>✓</i> No card required</span><span><i>✓</i> UK-based support</span><span><i>✓</i> One connected ecosystem</span></div></div>
      <div className="hero-visual"><div className="portal-card"><div className="portal-card-head"><span><i className="status-dot" />Your CoreCare</span><small>One place to start</small></div><div className="portal-products">{PRODUCTS.slice(0, 5).map((product) => <button key={product.code} className={activeProduct.code === product.code ? "active" : ""} onClick={() => setActiveProduct(product)}><i style={{ background: product.soft, color: product.accent }}>{product.icon}</i><span><strong>{product.shortName}</strong><small>{product.eyebrow}</small></span><b>→</b></button>)}</div></div><div className="hero-product-screen"><ProductMock product={activeProduct} compact /></div><div className="floating-note"><i>✓</i><span><strong>Right place, straight away</strong><small>Your account opens the product you use.</small></span></div></div>
    </div></section>
    <section className="suite-band"><div className="site-shell suite-row"><span>One connected CoreCare suite</span>{PRODUCTS.map((product) => <span className="suite-name" key={product.code}>{product.shortName}</span>)}</div></section>
    <section className="section products-section" id="products"><div className="site-shell"><div className="section-heading split-heading"><div><p className="eyebrow">Purpose-built products</p><h2>Software shaped around<br />the way you work.</h2></div><p>Choose one product or bring the suite together. Every workspace uses the same clear design, secure foundations and joined-up support.</p></div><div className="product-grid">{PRODUCTS.map((product, index) => <article className={`product-card product-card-${index + 1}`} key={product.code} style={{ "--product-accent": product.accent, "--product-soft": product.soft } as React.CSSProperties}><div className="product-card-top"><span className="product-icon">{product.icon}</span><span className="product-number">0{index + 1}</span></div><p className="card-eyebrow">{product.eyebrow}</p><h3>{product.name}</h3><p>{product.description}</p><ul>{product.features.map((feature) => <li key={feature}><span>✓</span>{feature}</li>)}</ul><div className="product-card-actions"><a href="#demo" onClick={() => setActiveProduct(product)}>View demonstration <Arrow /></a>{product.trialAvailable ? <Link href={`/trial?product=${product.code}`}>Try free</Link> : <Link href="/login?product=PLATFORM">Owner login</Link>}</div></article>)}</div></div></section>
    <section className="section demo-section" id="demo"><div className="site-shell"><div className="section-heading centered-heading"><p className="eyebrow light-eyebrow">A closer look</p><h2>See the work. Not the software.</h2><p>Pick a CoreCare product to explore a representative day-to-day workspace.</p></div><div className="demo-tabs" role="tablist" aria-label="Product demonstrations">{PRODUCTS.map((product) => <button key={product.code} role="tab" aria-selected={activeProduct.code === product.code} className={activeProduct.code === product.code ? "active" : ""} onClick={() => setActiveProduct(product)}><i style={{ background: product.soft, color: product.accent }}>{product.icon}</i>{product.shortName}</button>)}</div><div className="demo-stage"><div className="demo-copy"><p className="eyebrow">{activeProduct.eyebrow}</p><h3>{activeProduct.name}</h3><p>{activeProduct.description}</p><ul>{activeProduct.features.map((feature) => <li key={feature}><span>✓</span>{feature}</li>)}</ul><div className="demo-actions">{activeProduct.trialAvailable ? <Link className="button" href={`/trial?product=${activeProduct.code}`}>Try {activeProduct.shortName} free <Arrow /></Link> : <Link className="button" href="/login?product=PLATFORM">Owner platform login <Arrow /></Link>}<a className="demo-live-link" href={activeProduct.liveUrl}>Open current system <Arrow /></a></div></div><ProductMock product={activeProduct} /></div></div></section>
    <section className="section why-section" id="why-corecare"><div className="site-shell why-grid"><div className="why-copy"><p className="eyebrow">Designed as one ecosystem</p><h2>Specialist where it matters.<br />Connected everywhere else.</h2><p>CoreCare keeps each product focused on its industry while bringing account access, support and owner oversight into one recognisable experience.</p><Link className="secondary-button dark-secondary" href="/login">Go to your account <Arrow /></Link></div><div className="connection-map"><div className="connection-centre"><span className="brand-mark" aria-hidden="true"><i /><i /></span><strong>One CoreCare<br />account</strong></div>{PRODUCTS.slice(0, 5).map((product, index) => <div className={`connection-product connection-${index + 1}`} key={product.code} style={{ "--product-accent": product.accent, "--product-soft": product.soft } as React.CSSProperties}><i>{product.icon}</i><span>{product.shortName}</span></div>)}</div></div><div className="site-shell benefits-grid"><article><span>01</span><h3>One familiar experience</h3><p>The same clear navigation, visual language and support journey across every product.</p></article><article><span>02</span><h3>Access that knows where to go</h3><p>Your email and account entitlement guide you to the right workspace, with a clear choice if you use more than one.</p></article><article><span>03</span><h3>One team behind the suite</h3><p>Connected product health, support tickets and owner controls make help faster and more informed.</p></article></div></section>
    <section className="section trial-section"><div className="site-shell trial-panel"><div className="trial-copy"><p className="eyebrow light-eyebrow">30 days to explore</p><h2>Try the product that fits your business.</h2><p>Start without a payment card. We’ll keep your trial dates clear and help you choose the right plan when the 30 days are complete.</p><Link className="button light-button" href="/trial">Start your free trial <Arrow /></Link></div><div className="trial-timeline"><article><span>Today</span><i>1</i><div><strong>Choose your product</strong><small>Tell us a little about your organisation.</small></div></article><article><span>Day 1</span><i>2</i><div><strong>Open your workspace</strong><small>Your setup and trial dates are kept together.</small></div></article><article><span>Day 30</span><i>3</i><div><strong>Choose what happens next</strong><small>Continue on a paid plan or simply let the trial end.</small></div></article></div></div></section>
    <section className="section faq-section" id="questions"><div className="site-shell faq-grid"><div><p className="eyebrow">Common questions</p><h2>Good to know<br />before you begin.</h2><p>Need a more specific answer? Start a trial and tell us what you need from CoreCare.</p></div><div className="faq-list"><details open><summary>Can I use more than one CoreCare product?<span>+</span></summary><p>Yes. Your organisation can use one product or a combination, with the account portal guiding each person to the products available to them.</p></details><details><summary>Do I need a payment card for the trial?<span>+</span></summary><p>No. The 30-day trial begins without taking card details. Before it ends, you can choose whether to continue on a paid plan.</p></details><details><summary>Where will my products live?<span>+</span></summary><p>The planned structure keeps everything under corecaresystems.co.uk, with a clear subdomain for each product and one account entry point.</p></details><details><summary>Is the Owner Platform available to customers?<span>+</span></summary><p>No. The Owner Platform is a protected CoreCare operations workspace. Customer teams sign in to the individual products assigned to them.</p></details></div></div></section>
    <footer><div className="site-shell footer-grid"><div className="footer-brand"><Brand inverse /><p>One connected family of practical business software.</p></div><div><strong>Products</strong>{PRODUCTS.slice(0, 5).map((product) => <a key={product.code} href="#products">{product.shortName}</a>)}</div><div><strong>Get started</strong><Link href="/trial">30-day free trial</Link><Link href="/login">Customer login</Link><Link href="/login?product=PLATFORM">Owner Platform</Link></div><div><strong>CoreCare Systems</strong><a href="mailto:hello@corecaresystems.co.uk">hello@corecaresystems.co.uk</a><span>United Kingdom</span></div></div><div className="site-shell footer-bottom"><span>© {new Date().getFullYear()} CoreCare Systems</span><span>Built for better working days.</span></div></footer>
  </main>;
}
