import type { ProductCode } from "./products";

export type SolutionPage = { slug: string; title: string; description: string; productCode: ProductCode; audience: string; challenges: string[]; approach: string[]; questions: { question: string; answer: string }[] };

export const SOLUTIONS: SolutionPage[] = [
  { slug: "domiciliary-care-management-software", title: "Domiciliary care management software", description: "A practical way to connect care plans, risk, rotas, visits and manager oversight without assuming every provider works identically.", productCode: "CARE", audience: "For UK domiciliary and community care providers reviewing how staff, visits, care information and exceptions are coordinated.", challenges: ["Care information is spread between paper, spreadsheets and messages", "Coordinators see changes too late", "Managers spend time assembling evidence instead of reviewing exceptions"], approach: ["Map roles, branches and approval responsibilities", "Evaluate representative care, rota and visit workflows", "Agree governance, migration and readiness before using real care data"], questions: [{ question: "Can we use real service-user information in the trial?", answer: "The initial evaluation uses representative information. Real data is introduced only after security, governance and migration arrangements are agreed." }, { question: "Is this automatically suitable for every CQC-regulated provider?", answer: "No. The provider remains responsible for regulatory and clinical governance and must approve the production scope." }] },
  { slug: "care-rota-and-emar-software", title: "Care rota and eMAR software", description: "Evaluate joined-up scheduling, live visit oversight and medication workflows while keeping governance decisions explicit.", productCode: "CARE", audience: "For care teams comparing rota, visit and medication workflows and wanting one operational view.", challenges: ["Recurring rota changes are hard to communicate", "Medication and visit exceptions sit in separate systems", "Managers lack a timely view of incomplete activity"], approach: ["Test representative rota and visit scenarios", "Review medication and incident responsibility", "Confirm EVV, payroll, alerts and mobile requirements before live use"], questions: [{ question: "Does CoreCare promise offline eMAR?", answer: "No. A stable connection is currently required unless an accepted order expressly states otherwise." }, { question: "Are payroll and electronic call monitoring included?", answer: "Those requirements and integrations must be confirmed during scope; they are not assumed." }] },
  { slug: "campsite-booking-software", title: "Campsite booking software", description: "Bring pitches, units, guests, arrivals and site tasks into a clearer shared register.", productCode: "CAMPSITE", audience: "For independent campsites and holiday parks replacing fragmented calendars, notebooks and inboxes.", challenges: ["Availability differs between calendars and team members", "Arrival and balance information is difficult to share", "Occupancy reporting takes manual work"], approach: ["Map every pitch, unit and seasonal rule", "Assess and reconcile existing bookings", "Confirm website, payment and channel connections before launch"], questions: [{ question: "Can current bookings be imported?", answer: "Potentially. The source is assessed and a checked migration plan is agreed before any import." }, { question: "Is online booking included automatically?", answer: "No. Website, payment and channel-provider compatibility is confirmed for the customer’s setup." }] },
  { slug: "garage-job-card-software", title: "Garage job-card software", description: "Keep bookings, inspections, estimates and workshop progress connected to each customer and vehicle.", productCode: "GARAGE", audience: "For independent garages that want reception and technicians working from a consistent job record.", challenges: ["Diary changes do not reach the workshop", "Findings and approvals are split across paper and messages", "Customers call because job progress is unclear"], approach: ["Map bays, services and job stages", "Test a representative job from booking to collection", "Scope MOT, parts, messaging, payments and accounts connections"], questions: [{ question: "Does it connect to MOT and parts suppliers?", answer: "Compatibility depends on the exact provider and must be confirmed before it forms part of the order." }, { question: "Can vehicle history be moved?", answer: "Source quality is assessed first, then the import and customer validation method are agreed." }] },
  { slug: "workshop-management-software", title: "UK workshop management software", description: "A shared operational view for the diary, workload, vehicles, inspections and outstanding customer actions.", productCode: "GARAGE", audience: "For UK workshops comparing a browser-based workflow with paper job cards or disconnected systems.", challenges: ["Workload and bay capacity are not visible together", "Incomplete estimates and parts actions are missed", "Historic vehicle context is hard to retrieve"], approach: ["Define reception and technician permissions", "Agree the job status and inspection workflow", "Validate devices, migration and supplier connections before production"], questions: [{ question: "What devices are supported?", answer: "Modern desktop and tablet browsers are the baseline; workshop devices should be tested in the actual environment." }, { question: "Does it work offline?", answer: "Offline workshop operation is not currently promised." }] },
  { slug: "hospitality-pos-software", title: "Pub and restaurant POS software", description: "Evaluate ordering, menus, kitchen progress and service visibility with representative venue data.", productCode: "POS", audience: "For independent pubs, restaurants and hospitality venues reviewing a modern browser-based till and kitchen workflow.", challenges: ["Order changes and kitchen updates become disconnected", "Menu changes take too long to reach the till", "Open tables, collections and service status are difficult to see"], approach: ["Map service types, menu structure and kitchen stations", "Test the full front-to-back service flow", "Verify card terminals, printers, devices and network resilience"], questions: [{ question: "Will it work with our card terminal and printer?", answer: "The exact models and providers must be tested before installation; universal compatibility is not claimed." }, { question: "Can we trade offline?", answer: "Guaranteed offline trading is not currently offered." }] },
  { slug: "small-business-finance-software", title: "Small-business finance software", description: "Keep everyday finance records, reconciliation and management visibility together without presenting software as professional advice.", productCode: "FINANCE", audience: "For UK sole traders and small organisations that want clearer operational finance information and adviser review.", challenges: ["Invoices, cash and journals are held in disconnected files", "Reconciliation is difficult to review", "Management information arrives too late"], approach: ["Review chart of accounts and responsibilities", "Validate opening balances and historical records", "Confirm HMRC, bank-feed, statutory and adviser requirements"], questions: [{ question: "Does it include every HMRC submission?", answer: "No universal statutory-submission claim is made. Exact tax and reporting needs are confirmed before production use." }, { question: "Does it replace an accountant?", answer: "No. It is an operational finance workspace and is not accounting, tax or legal advice." }] },
];

export function getSolution(slug: string) { return SOLUTIONS.find((solution) => solution.slug === slug); }
