import type { Metadata } from "next";
import { MarketingShell } from "../site-chrome";

export const metadata: Metadata = { title: "Cookie notice", description: "Cookies and server-side service events used by the CoreCare website and products.", alternates: { canonical: "/cookies" } };

export default function CookiesPage() {
  return <MarketingShell><section className="content-hero compact-content-hero"><div className="site-shell narrow-heading"><p className="eyebrow">Cookie notice</p><h1>Essential cookies, clearly explained.</h1><p className="content-lead">The public CoreCare website does not currently set advertising or cross-site analytics cookies. Cookies may be used only when needed for security or a product sign-in.</p><p className="updated-note">Last updated 5 August 2026</p></div></section><section className="section legal-section"><div className="site-shell legal-copy">
    <h2>Public website</h2><p>CoreCare records limited service events on the server, such as whether a form was saved or failed. These events help us operate and protect the site; they are not browser cookies and are not used to follow you across unrelated websites.</p>
    <h2>Cloudflare security cookies</h2><p>Cloudflare may set a strictly necessary cookie when a visitor is asked to complete a security check or when a configured security feature needs to distinguish requests. Depending on the protection triggered, names can include <code>cf_clearance</code>, <code>__cf_bm</code> or <code>_cfuvid</code>. They support challenge clearance, bot protection or rate limiting and are controlled by Cloudflare. They are not set for advertising. See <a href="https://developers.cloudflare.com/fundamentals/reference/policies-compliances/cloudflare-cookies/" rel="noreferrer">Cloudflare’s current cookie reference</a>.</p>
    <h2>CoreCare product session cookies</h2><div className="legal-table-wrap"><table><thead><tr><th>Cookie</th><th>Used by</th><th>Purpose</th><th>Typical lifetime</th></tr></thead><tbody><tr><td><code>corecare_session</code></td><td>Care, Campsites, Garage and private operational services</td><td>Keep an authenticated user signed in to that product.</td><td>Up to 12 hours</td></tr><tr><td><code>corecare_finance_session</code></td><td>Finance</td><td>Keep an authenticated Finance user signed in.</td><td>Up to 12 hours</td></tr><tr><td><code>cc_pos_session</code></td><td>POS</td><td>Keep an authenticated POS user signed in.</td><td>Up to 12 hours</td></tr></tbody></table></div><p>Each product owns its own session and database. The public login page does not create one shared cookie that unlocks every product. A session may end sooner after sign-out, expiry or a security action.</p>
    <h2>Why there is no cookie banner</h2><p>The site currently uses no optional advertising or browser analytics cookies. Strictly necessary security and login cookies are used to deliver a service the visitor requests. If optional cookies are introduced, CoreCare will update this notice and obtain the choice required before setting them.</p>
    <h2>Managing cookies</h2><p>You can remove or block cookies in your browser. Security checks and product login may stop working if essential cookies are blocked. Closing a browser does not necessarily remove a cookie before its stated expiry.</p>
    <h2>Questions</h2><p>Email <a href="mailto:privacy@corecaresystems.co.uk">privacy@corecaresystems.co.uk</a> if you want information about a particular cookie or server-side service event.</p>
  </div></section></MarketingShell>;
}
