import type { Metadata } from "next";
import Link from "next/link";
import { Arrow, MarketingShell } from "../site-chrome";

export const metadata: Metadata = { title: "Security controls and assurance", description: "Verified CoreCare controls, known gaps, production gates, recovery position and responsible disclosure.", alternates: { canonical: "/security" } };

const verification = [
  ["Password storage", "Verified with qualification", "Care, Campsites, Finance and POS use salted PBKDF2-SHA-256 password hashing. Garage delegates credential validation to its configured upstream authentication service."],
  ["Website login and public forms", "Verified", "The public login, trial, contact, checkout, password-activation and privacy-request routes use server-side rate limiting and same-origin checks where applicable."],
  ["Session cookies", "Verified in product source/tests", "Product session cookies are HttpOnly, Secure and SameSite. Each product creates and validates its own session."],
  ["Organisation separation", "Verified in source; independent test pending", "Product data access is scoped by organisation, tenant, property, site or workshop identifiers on the server. Independent adversarial tenant-isolation testing has not yet been completed."],
  ["Support access", "Verified in source/tests", "Configured cross-product support sessions are time-limited, record purpose and access mode, and support read-only restrictions where provided."],
  ["Audit records", "Verified in source", "Products contain durable database audit/compliance tables for authentication, support access and significant mutations. Coverage continues to be reviewed per route."],
  ["Sensitive logging", "Partially verified", "The public site’s analytics table stores event, product, route and outcome rather than form payloads. A full independent log-content review across every provider has not yet been completed."],
  ["Product data separation", "Verified by configuration", "The five customer products are deployed as separate Workers with separate product database bindings and product-owned sessions."],
  ["Backup restoration", "Recovery facility available; restore evidence pending", "Cloudflare D1 recovery facilities are available, but CoreCare does not yet claim a completed product-by-product restore exercise or universal RPO/RTO."],
  ["Multi-factor authentication", "Not universal", "MFA is not yet available to every customer-product privileged account and remains a production-readiness requirement for higher-risk deployments."],
  ["Independent security testing", "Not yet claimed", "The complete suite has not yet received an independent penetration test or CoreCare-level ISO 27001, Cyber Essentials or SOC 2 certification."],
];

export default function SecurityPage() {
  return <MarketingShell><section className="content-hero"><div className="site-shell narrow-heading"><p className="eyebrow">Security at CoreCare</p><h1>Verified controls, known gaps and clear gates.</h1><p className="content-lead">This statement separates controls found in the current product source from assurance work that is still required. A guided evaluation is not approval to introduce sensitive production data.</p><p className="updated-note">Source review updated 5 August 2026</p></div></section>
    <section className="section"><div className="site-shell legal-copy wide-legal-copy"><p className="eyebrow">Control verification</p><h2>What has been checked</h2><div className="legal-table-wrap"><table><thead><tr><th>Control</th><th>Current position</th><th>Evidence and qualification</th></tr></thead><tbody>{verification.map(([control, status, evidence]) => <tr key={control}><td><strong>{control}</strong></td><td><span className="status-label">{status}</span></td><td>{evidence}</td></tr>)}</tbody></table></div></div></section>
    <section className="section process-section"><div className="site-shell"><div className="section-heading split-heading"><div><p className="eyebrow">Production security gates</p><h2>Required before sensitive or high-risk use.</h2></div><p>The order and readiness record must identify who approved each applicable control. A marketing page cannot replace implementation evidence.</p></div><div className="process-grid"><article><span>01</span><h3>Privileged MFA</h3><p>Require MFA for owners, administrators, managers, finance, support and export-capable roles, or document an approved compensating control.</p></article><article><span>02</span><h3>Isolation tests</h3><p>Complete negative tests for tenant, organisation, branch, site and support access against the deployed release.</p></article><article><span>03</span><h3>Restore exercise</h3><p>Restore each production data store to an isolated target and record recovery point, time, validation and responsibility.</p></article><article><span>04</span><h3>Independent review</h3><p>Run dependency, secret, static, authentication, access-control, session, upload and API-abuse testing, followed by an external penetration test for higher-risk products.</p></article></div></div></section>
    <section className="section"><div className="site-shell prose-grid"><article><h2>Encryption and transport</h2><p>Production access uses HTTPS/TLS. Cloudflare documents encryption at rest for D1 databases and R2 objects. CoreCare does not claim customer-managed keys or UK-only storage unless a customer order expressly confirms them.</p></article><article><h2>Recovery commitments</h2><p>Backup frequency, recovery-point objective, recovery-time objective, retention, restore-test frequency and customer communication are product/order-specific until restore exercises support a common published baseline.</p><p>This is intentionally more limited than saying “backups are tested”.</p></article><article><h2>Customer operation</h2><p>Customers should keep accounts individual, choose unique passwords, review roles, remove leavers promptly, secure their own devices and keep regulated information out of representative trials unless expressly approved.</p></article><article><h2>Assurance boundary</h2><p>Cloudflare provider certifications do not certify CoreCare itself. CoreCare will publish a certification or independent test only after the scope, date and unresolved findings can be stated accurately.</p></article></div></section>
    <section className="section process-section"><div className="site-shell"><div className="section-heading split-heading"><div><p className="eyebrow">Personal data breach response</p><h2>Contain, assess, notify and learn.</h2></div><p>Every suspected breach receives a central record, including events that do not meet a notification threshold.</p></div><div className="process-grid"><article><span>01</span><h3>Record and contain</h3><p>Start a timestamped case, preserve evidence, restrict affected access and stop further loss where proportionate.</p></article><article><span>02</span><h3>Assess risk</h3><p>Identify data, people, systems, scale, likely consequences, customer roles and available mitigation.</p></article><article><span>03</span><h3>Notify</h3><p>Support the controller’s decision. Where CoreCare is controller, report qualifying risk to the ICO within 72 hours of awareness and inform people without undue delay where high risk applies.</p></article><article><span>04</span><h3>Recover and learn</h3><p>Validate recovery, document the decision, communicate in phases where needed and track corrective actions to completion.</p></article></div></div></section>
    <section className="section"><div className="site-shell evidence-grid"><article><p className="eyebrow">Data lifecycle</p><h2>Retention, export and deletion.</h2><p>Product retention follows customer instructions, legal holds and the agreed service. Data return and deletion are handled under the DPA and customer terms.</p><Link href="/data-retention">Read the retention policy <Arrow /></Link></article><article><p className="eyebrow">Responsible disclosure</p><h2>Report a security concern.</h2><p>Email the product, affected URL, time observed and a safe description. Do not send passwords, health data, payment information or harmful exploit data by ordinary email.</p><a href="mailto:security@corecaresystems.co.uk?subject=Security%20concern">security@corecaresystems.co.uk <Arrow /></a></article></div></section>
  </MarketingShell>;
}
