import type { Metadata } from "next";
import Link from "next/link";
import { Arrow, MarketingShell } from "../site-chrome";

export const metadata: Metadata = { title: "Security and responsible disclosure", description: "CoreCare access controls, encryption, audit, recovery, incident handling and responsible disclosure.", alternates: { canonical: "/security" } };

export default function SecurityPage() {
  return <MarketingShell><section className="content-hero"><div className="site-shell narrow-heading"><p className="eyebrow">Security at CoreCare</p><h1>Layered controls, stated without shortcuts.</h1><p className="content-lead">CoreCare combines application controls with Cloudflare-hosted network, compute, database and object-storage protections. Product-specific requirements are confirmed during onboarding.</p><p className="updated-note">Control statement reviewed 5 August 2026</p></div></section>
    <section className="section"><div className="site-shell prose-grid"><article><h2>Accounts and sessions</h2><p>Each product validates registered accounts and creates an expiring session. Passwords use salted, one-way hashing. Login and public-form requests are rate limited. Session cookies are restricted from browser scripts, marked Secure and use a SameSite policy.</p><p>The public login routes a user to the selected registered product; it does not turn one product cookie into a master key for the whole suite.</p></article><article><h2>Access and separation</h2><p>Roles, product entitlements and organisation boundaries are checked on the server. Product databases and sessions are separated where configured. Owner Platform support access is time-limited and recorded, and can be read-only.</p><p>The Owner Platform has an additional Cloudflare identity layer. CoreCare does not yet claim that MFA is universally available to every customer-product account.</p></article><article><h2>Encryption</h2><p>Production access uses HTTPS/TLS. Cloudflare D1 database objects and metadata are encrypted at rest using AES-256 GCM, and D1 connections use TLS or HTTPS. R2 objects and metadata are encrypted at rest using AES-256 GCM and protected in transit with TLS.</p><p>CoreCare does not claim customer-managed encryption keys or UK-only data location unless a customer order expressly confirms those controls.</p></article><article><h2>Audit and observability</h2><p>CoreCare records authentication, support and significant product changes in durable product or Platform audit tables. The Owner Platform creates integrity checkpoints for its central audit stream. Request identifiers and structured operational logs support fault investigation without intentionally recording passwords or full sensitive payloads.</p><p>Provider console logs have shorter retention than product audit records and are not treated as the legal audit register.</p></article><article><h2>Recovery and retention</h2><p>D1 recovery facilities and product backups support restoration. Recovery windows and restore objectives depend on the enabled Cloudflare plan and product configuration. Retention actions use documented categories and legal holds; live customer records are not silently deleted under a generic period.</p><p>Read the <Link href="/data-retention">retention policy</Link> and confirm any sector-specific requirements during onboarding.</p></article><article><h2>Secure operation</h2><p>Customers should keep accounts individual, use unique passwords, review roles, remove leavers promptly and keep regulated information out of demonstrations unless expressly approved. Support access must be authorised, limited to the task and handled through the agreed route.</p></article></div></section>
    <section className="section process-section"><div className="site-shell"><div className="section-heading split-heading"><div><p className="eyebrow">Personal data breach response</p><h2>Contain, assess, notify and learn.</h2></div><p>Every suspected breach receives a central record, including events that do not meet a notification threshold.</p></div><div className="process-grid"><article><span>01</span><h3>Record and contain</h3><p>Start a timestamped case, preserve evidence, restrict affected access and stop further loss where proportionate.</p></article><article><span>02</span><h3>Assess risk</h3><p>Identify data, people, systems, scale, likely consequences, customer roles and available mitigation.</p></article><article><span>03</span><h3>Notify</h3><p>Support the controller’s decision. Where CoreCare is controller, report qualifying risk to the ICO within 72 hours of awareness and inform people without undue delay where high risk applies.</p></article><article><span>04</span><h3>Recover and learn</h3><p>Validate recovery, document the decision, communicate in phases where needed and track corrective actions to completion.</p></article></div></div></section>
    <section className="section"><div className="site-shell evidence-grid"><article><p className="eyebrow">Independent assurance</p><h2>What we do not claim.</h2><p>CoreCare does not currently claim that the whole suite is independently penetration tested or certified to ISO 27001, Cyber Essentials, SOC 2 or another security standard. A provider certification is not certification of CoreCare itself.</p></article><article><p className="eyebrow">Customer due diligence</p><h2>Ask before you rely.</h2><p>Before production use, confirm data location, recovery objectives, restore testing, subprocessors, deletion, support access, incident notification and sector-specific controls.</p><Link href="/compliance">Open the compliance library <Arrow /></Link></article></div></section>
    <section className="section"><div className="site-shell security-contact"><h2>Report a security concern</h2><p>Email a concise description, affected URL or product, time observed and a safe way to contact you. Do not send passwords, health data, payment information or harmful exploit data by ordinary email. If personal information may have been exposed, mark the message “possible personal data breach”.</p><a className="button" href="mailto:security@corecaresystems.co.uk?subject=Security%20concern">Email security@corecaresystems.co.uk <Arrow /></a></div></section>
  </MarketingShell>;
}
