import type { Metadata } from "next";
import { COMPANY_ADDRESS, COMPANY_DETAILS } from "../company-details";
import { MarketingShell } from "../site-chrome";

export const metadata: Metadata = { title: "Customer terms and conditions", description: "CoreCare Systems subscription and product service terms for business customers.", alternates: { canonical: "/customer-terms" } };

export default function CustomerTermsPage() {
  return <MarketingShell><section className="content-hero compact-content-hero"><div className="site-shell narrow-heading"><p className="eyebrow">Customer terms and conditions</p><h1>The operating terms for a CoreCare subscription.</h1><p className="content-lead">These business-to-business terms apply only when an order, proposal or checkout expressly incorporates them.</p><p className="updated-note">Version 1.0 · 5 August 2026</p></div></section><section className="section legal-section"><div className="site-shell legal-copy">
    <h2>1. Parties and agreement</h2><p>The supplier is {COMPANY_DETAILS.legalName}, trading from {COMPANY_ADDRESS}, {COMPANY_DETAILS.country} (“CoreCare”). The customer is the organisation identified in the accepted order. The agreement consists of the order, these terms, the <a href="/data-processing-agreement">DPA</a>, the service description and any agreed schedules. The order takes priority for its commercial details.</p>
    <h2>2. Service and permitted use</h2><p>CoreCare grants the customer a non-exclusive, non-transferable right during the subscription term for authorised users to use the ordered products for the customer’s internal business. The customer must use the service lawfully, keep accounts individual, protect credentials, maintain accurate administrators and prevent unauthorised access. The customer must not resell, reverse engineer, probe, disrupt or use the service to infringe another person’s rights.</p>
    <h2>3. Setup, trials and changes</h2><p>A 30-day trial begins when the workspace is activated and does not become paid without an express purchase. Trial services may contain limits and must not be used for live sensitive or regulated records unless approved in writing. CoreCare may improve or change features during a subscription, but will not materially remove the core function of a paid service without reasonable notice or an appropriate remedy.</p>
    <h2>4. Charges and payment</h2><p>The order states the price, billing period, taxes and payment method. CoreCare will not charge a trial user unless the customer actively accepts a paid order or checkout. Paid invoices are due on the date stated. If an undisputed amount remains overdue after notice, CoreCare may restrict the service to read-only access or suspend it, while preserving reasonable access to export data where lawful and technically possible.</p>
    <h2>5. Customer data and privacy</h2><p>The customer retains its rights in Customer Data and gives CoreCare the permissions needed to provide, secure and support the service. Each party will comply with applicable data protection law. For Customer Personal Data processed on the customer’s behalf, the DPA applies. The customer is responsible for lawful collection, notices, user access, data quality and retention instructions.</p>
    <h2>6. Security and support</h2><p>CoreCare will maintain reasonable safeguards described in the DPA and security information. The customer will report suspected compromise promptly and cooperate with containment. Support scope, response targets and any service level commitment apply only if stated in the order. Planned maintenance and urgent security work may temporarily affect availability.</p>
    <h2>7. Intellectual property</h2><p>CoreCare and its licensors retain rights in the products, software, documentation, design and service improvements. The customer retains rights in Customer Data. Feedback may be used to improve the service without identifying the customer or disclosing confidential information.</p>
    <h2>8. Confidentiality</h2><p>Each party will protect the other’s confidential information using reasonable care, use it only for the agreement and disclose it only to people who need it and are bound to confidentiality. These duties do not cover information that is public without breach, independently developed, lawfully received without restriction or required to be disclosed by law. Where lawful, the receiving party will give advance notice of compelled disclosure.</p>
    <h2>9. Suspension and termination</h2><p>Either party may terminate for a material breach not remedied within 30 days of written notice, or immediately for insolvency where law permits. CoreCare may suspend access where reasonably necessary to contain a security threat, prevent unlawful use or address non-payment after notice. On termination, charges accrued remain payable and data return and deletion follow the DPA and retention policy.</p>
    <h2>10. Warranties and liability</h2><p>CoreCare will provide the service with reasonable skill and care. Except as expressly stated, the service is provided without implied warranties to the fullest extent permitted by law and is not a substitute for the customer’s professional judgement, statutory duties, clinical decisions, accounting advice or business continuity arrangements. Neither party excludes liability that cannot lawfully be excluded, including liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation. Any other liability cap or excluded loss must be stated in the order; if it is not, the parties should agree it before paid production use.</p>
    <h2>11. General</h2><p>Neither party may assign the agreement without the other’s consent, not to be unreasonably withheld, except as part of a genuine transfer of its business with appropriate safeguards. Delay is not a waiver. Invalid provisions are adjusted only as needed. Notices must be sent to the contact in the order; legal notices to CoreCare may also be sent to the trading address and <a href="mailto:hello@corecaresystems.co.uk">hello@corecaresystems.co.uk</a>. The agreement is governed by the law of England and Wales, and its courts have jurisdiction, unless the order lawfully states otherwise.</p>
  </div></section></MarketingShell>;
}
